unbind r
bind r source-file ~/.tmux.conf
set -s set-clipboard on
set -g prefix C-s                  # Leader = Ctrl-s
setw -g mode-keys vi               # Vim-like keys
set -g mouse on                    # Enable mouse
set -g monitor-activity on         # Notify activity in other windows
set -g visual-activity on
set -g status-position top
set -as terminal-features ',screen-256color:clipboard'
# Pane navigation (vim-like)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n C-e clear-history          # Clear scrollback
# for yazi 
# set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
# Copy-mode (vi-style selection)
bind -T copy-mode-vi v send -X begin-selection

# Use xsel (recommended for Linux clipboard)
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -b --clear" 
bind P paste-buffer                # Paste from buffer

# Fix mouse copy-paste (no clearing!)
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel -b --clear"

# Tmux Plugin Manager (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'        # Theme
run '~/.tmux/plugins/tpm/tpm'      # Initialize TPM
